[package]
name = "mcpnr-placement"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = "3.1.5"
itertools = "0.10"
mcpnr-common = { path = "../mcpnr-common" }
quartz_nbt = { version = "0.2", features = [ "serde" ] }
wgpu = "0.12.0"
winit = "0.26.1"
