[package]
name = "mcpnr-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
prost = "0.9.0"
serde = "1"

[build-dependencies]
prost-build = "0.9.0"
